<a href="https://colab.research.google.com/github/akhiluthappa1/data_science/blob/main/Akhil_Uthappa_Assignment_10_Stock_market_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

pd.set_option("display.width",1000)
df = pd.read_csv("/content/AAPL_weekly_return_volatility (1) - AAPL_weekly_return_volatility (1).csv",sep=",")
df

     Year  Week_Number  mean_return  volatility labels
0    2020            0     -0.48600    0.687308    Red
1    2020            1      0.85720    1.040851  Green
2    2020            2      0.54340    1.404286  Green
3    2020            3     -0.03175    0.547226    Red
4    2020            4     -0.51960    3.137070    Red
..    ...          ...          ...         ...    ...
100  2021           48      0.64780    1.904606  Green
101  2021           49      2.09540    1.445607  Green
102  2021           50     -0.91880    2.482887    Red
103  2021           51      0.74825    1.230668  Green
104  2021           52      0.27800    1.382687  Green

[105 rows x 5 columns]

In [15]:
df['Label'] = np.where(df['labels']=='Red', 0, 1)
df

     Year  Week_Number  mean_return  volatility labels  Label
0    2020            0     -0.48600    0.687308    Red      0
1    2020            1      0.85720    1.040851  Green      1
2    2020            2      0.54340    1.404286  Green      1
3    2020            3     -0.03175    0.547226    Red      0
4    2020            4     -0.51960    3.137070    Red      0
..    ...          ...          ...         ...    ...    ...
100  2021           48      0.64780    1.904606  Green      1
101  2021           49      2.09540    1.445607  Green      1
102  2021           50     -0.91880    2.482887    Red      0
103  2021           51      0.74825    1.230668  Green      1
104  2021           52      0.27800    1.382687  Green      1

[105 rows x 6 columns]

In [24]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
X_train = df[df['Year']==2020]
X_test = df[df['Year']==2021]
Y_train = X_train['Label']
X_train = X_train.drop(['Label', 'labels', 'Year', 'Week_Number'], axis=1)
Y_test = X_test['Label']
X_test = X_test.drop(['Label', 'labels', 'Year', 'Week_Number'], axis=1)
clf = QuadraticDiscriminantAnalysis()
clf.fit(X_train, Y_train)
Y_pred_QDA = clf.predict(X_test)
print(Y_pred_QDA)

[0 0 1 0 1 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 0
 1 0 1 1 1 1 1 1 1 0 1 1 0 1 1]

In [25]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
model = LinearDiscriminantAnalysis()
model.fit(X_train, Y_train)
Y_pred_LDA = model.predict(X_test)
print(Y_pred_LDA)

[0 0 1 0 1 0 0 0 1 0 0 1 1 1 1 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 1 1 0 0 1 0 0
 1 0 0 1 1 1 1 0 1 0 1 1 0 1 1]

In [29]:
from sklearn.metrics import accuracy_score
QDA_acc = accuracy_score(Y_test, Y_pred_QDA)
LDA_acc = accuracy_score(Y_test, Y_pred_LDA)
print("ACCURACY OF QDA---->", QDA_acc)
print("\n\nACCURACY OF LDA---->", LDA_acc)

ACCURACY OF QDA----> 0.75


ACCURACY OF LDA----> 0.8076923076923077

In [31]:
from sklearn.metrics import confusion_matrix
QDA_conf = confusion_matrix(Y_test, Y_pred_QDA)
LDA_conf = confusion_matrix(Y_test, Y_pred_LDA)
print("CONFUSION MATRIX OF QDA---->\n", QDA_conf)
print("\n\CONFUSION MATRIX OF LDA---->\n", LDA_conf)

CONFUSION MATRIX OF QDA---->
 [[18 12]
 [ 1 21]]

\CONFUSION MATRIX OF LDA---->
 [[22  8]
 [ 2 20]]

In [33]:
TPR_QDA = QDA_conf[0][0]/(QDA_conf[0][0]+QDA_conf[1][0])
TNR_QDA = QDA_conf[1][1]/QDA_conf[1][1]+QDA_conf[0][1]
TPR_LDA = LDA_conf[0][0]/(LDA_conf[0][0]+LDA_conf[1][0])
TNR_LDA = LDA_conf[1][1]/LDA_conf[1][1]+LDA_conf[0][1]

print("TPR QDA---->", TPR_QDA)
print("TNR QDA---->", TNR_QDA)
print("TPR LDA---->", TPR_LDA)
print("TNR QDA---->", TNR_LDA)

TPR QDA----> 0.9473684210526315
TNR QDA----> 13.0
TPR LDA----> 0.9166666666666666
TNR QDA----> 9.0